export type {
  PartCategory,
  PartUnit,
  PartStatus,
  PartCriticality,
  StockStatus,
  CadFileType,
  MovementType,
  ReferenceType,
  RequestStatus,
  ReviewDecision,
  PurchaseOrderStatus,
  ImportSessionStatus,
  InventoryCurrency,
  ImportErrorCode,
  CadFile,
  RequestItem,
  StoreKeeperReview,
  SupervisorReview,
  PurchaseOrderItem,
  ImportError,
  InventoryPart,
  PartsRequest,
  StockMovement,
  PurchaseOrder,
  InventoryImportSession,
  InventorySettings,
  CreatePartPayload,
  UpdatePartPayload,
  ParsedPartRow,
  ValidationError,
  ParsedImportResult,
  ValidationResult,
  InventoryStats,
  ReceiveItem,
  ReceiveStockPayload,
} from '@/types/inventory';

export const VALID_UNITS = [
  'pcs', 'set', 'kg', 'g', 'L', 'mL', 'm', 'cm', 'box', 'roll', 'pair', 'bag', 'drum',
] as const;

export const VALID_CATEGORIES = [
  'bearings',
  'belts_chains',
  'bolts_fasteners',
  'electrical',
  'filters',
  'gaskets_seals',
  'gears_sprockets',
  'hydraulic',
  'lubricants_oils',
  'motors_drives',
  'pneumatic',
  'pumps_valves',
  'safety_equipment',
  'sensors_instrumentation',
  'welding_supplies',
  'other',
] as const;

import type { PartCategory, PartUnit } from '@/types/inventory';

export const CATEGORY_LABELS: Record<PartCategory, string> = {
  bearings: 'Bearings',
  belts_chains: 'Belts & Chains',
  bolts_fasteners: 'Bolts & Fasteners',
  electrical: 'Electrical',
  filters: 'Filters',
  gaskets_seals: 'Gaskets & Seals',
  gears_sprockets: 'Gears & Sprockets',
  hydraulic: 'Hydraulic',
  lubricants_oils: 'Lubricants & Oils',
  motors_drives: 'Motors & Drives',
  pneumatic: 'Pneumatic',
  pumps_valves: 'Pumps & Valves',
  safety_equipment: 'Safety Equipment',
  sensors_instrumentation: 'Sensors & Instrumentation',
  welding_supplies: 'Welding Supplies',
  other: 'Other',
};

export const UNIT_LABELS: Record<PartUnit, string> = {
  pcs: 'Pieces (pcs)',
  set: 'Set',
  kg: 'Kilograms (kg)',
  g: 'Grams (g)',
  L: 'Litres (L)',
  mL: 'Millilitres (mL)',
  m: 'Metres (m)',
  cm: 'Centimetres (cm)',
  box: 'Box',
  roll: 'Roll',
  pair: 'Pair',
  bag: 'Bag',
  drum: 'Drum',
};
