import { Timestamp } from 'firebase/firestore';
import type { TriageFlow } from '../../types/triage';

// Built-in triage templates surfaced in the Browse Templates view so the
// page is never empty when the Firestore `triageTemplates` collection hasn't
// been seeded yet. These are read-only references — users clone them into
// their own triage flows.
const now = Timestamp.fromDate(new Date());

export const BUILTIN_TRIAGE_TEMPLATES: TriageFlow[] = [
  {
    id: 'builtin-general-machine-fault',
    companyId: 'pulsemaint_templates',
    name: 'General Machine Fault',
    description: 'Generic triage flow for any machine fault. Covers safety isolation, fault assessment, and operator safe action.',
    machineTypeId: null,
    specificMachineId: null,
    language: 'en',
    isTemplate: true,
    isActive: true,
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
    updatedBy: 'system',
    emergencyContacts: [
      { name: 'Maintenance Manager', phone: '+94-XX-XXXXXXX', role: 'plant_manager' },
    ],
    machineShutdownProcedure:
      '1. Press RED Emergency Stop button\n2. Isolate power at MCC panel\n3. Apply LOTO tag\n4. Notify supervisor',
    totalEstimatedMinutes: 10,
    usageCount: 0,
    lastUsedAt: null,
    steps: [
      {
        id: 'gm-s1',
        stepNumber: 1,
        phase: 'safety',
        title: 'Check for Immediate Hazards',
        instruction: 'Before approaching the machine, check for smoke, sparks, fluid leaks, or unusual sounds. If any present, do NOT approach.',
        type: 'yes_no',
        options: [
          { id: 'gm-s1-y', label: 'No hazards visible', nextStepId: 'gm-s2', isEscalate: false, isSafe: true },
          { id: 'gm-s1-n', label: 'Hazard detected — STOP', nextStepId: null, isEscalate: true, isSafe: false },
        ],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'danger',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 30,
      },
      {
        id: 'gm-s2',
        stepNumber: 2,
        phase: 'safety',
        title: 'Isolate Power',
        instruction: 'Turn the machine OFF using the main control panel. Wait 30 seconds. Do NOT restart.',
        type: 'statement',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'caution',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: true,
        translations: {},
        estimatedSeconds: 60,
      },
      {
        id: 'gm-s3',
        stepNumber: 3,
        phase: 'assessment',
        title: 'Identify Fault Type',
        instruction: 'What type of fault have you identified?',
        type: 'multiple_choice',
        options: [
          { id: 'gm-s3-a', label: 'Noise / Vibration', nextStepId: 'gm-s4', isEscalate: false, isSafe: true },
          { id: 'gm-s3-b', label: 'No power / Not starting', nextStepId: 'gm-s4', isEscalate: false, isSafe: true },
          { id: 'gm-s3-c', label: 'Overheating', nextStepId: 'gm-s4', isEscalate: false, isSafe: false },
          { id: 'gm-s3-d', label: 'Fluid leak', nextStepId: 'gm-s5', isEscalate: false, isSafe: false },
          { id: 'gm-s3-e', label: 'Fire / Electrical fault', nextStepId: null, isEscalate: true, isSafe: false },
        ],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'caution',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 45,
      },
      {
        id: 'gm-s4',
        stepNumber: 4,
        phase: 'document',
        title: 'Photograph the Fault',
        instruction: 'Take clear photos of the affected area and any visible damage.',
        type: 'photo_required',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'safe',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: true,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 60,
      },
      {
        id: 'gm-s5',
        stepNumber: 5,
        phase: 'wait',
        title: 'Wait for Repair Team',
        instruction: 'You have completed the triage. Keep the area clear. Do not attempt any repairs. Repair team has been notified.',
        type: 'statement',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'safe',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: true,
        translations: {},
        estimatedSeconds: 30,
      },
    ],
  },
  {
    id: 'builtin-conveyor-belt-jam',
    companyId: 'pulsemaint_templates',
    name: 'Conveyor Belt Jam',
    description: 'Triage flow for conveyor belt jamming incidents. Includes jam clearance safety steps.',
    machineTypeId: 'conveyor',
    specificMachineId: null,
    language: 'en',
    isTemplate: true,
    isActive: true,
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
    updatedBy: 'system',
    emergencyContacts: [
      { name: 'Conveyor Supervisor', phone: '+94-XX-XXXXXXX', role: 'supervisor' },
    ],
    machineShutdownProcedure:
      '1. Press STOP on conveyor panel\n2. Lock isolator switch\n3. Apply LOTO tag\n4. Inform shift supervisor',
    totalEstimatedMinutes: 8,
    usageCount: 0,
    lastUsedAt: null,
    steps: [
      {
        id: 'cb-s1',
        stepNumber: 1,
        phase: 'safety',
        title: 'Stop the Conveyor',
        instruction: 'Press the STOP button immediately. Do NOT reach into the conveyor while it is running.',
        type: 'statement',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'danger',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: true,
        translations: {},
        estimatedSeconds: 30,
      },
      {
        id: 'cb-s2',
        stepNumber: 2,
        phase: 'assessment',
        title: 'Identify Jam Location',
        instruction: 'Inspect the belt and identify where the jam has occurred.',
        type: 'multiple_choice',
        options: [
          { id: 'cb-s2-a', label: 'Head/tail pulley', nextStepId: 'cb-s3', isEscalate: false, isSafe: true },
          { id: 'cb-s2-b', label: 'Mid-section', nextStepId: 'cb-s3', isEscalate: false, isSafe: true },
          { id: 'cb-s2-c', label: 'Material trapped in frame', nextStepId: 'cb-s3', isEscalate: false, isSafe: true },
          { id: 'cb-s2-d', label: 'Belt torn / damaged', nextStepId: null, isEscalate: true, isSafe: false },
        ],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'caution',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 60,
      },
      {
        id: 'cb-s3',
        stepNumber: 3,
        phase: 'safe_action',
        title: 'Clear the Jam Safely',
        instruction: 'Using tools (NOT bare hands), carefully remove jammed material. Wear gloves. Do not force the belt.',
        type: 'checklist',
        options: [],
        checklistItems: [
          { id: 'cb-c1', text: 'Gloves on', required: true },
          { id: 'cb-c2', text: 'Machine fully stopped', required: true },
          { id: 'cb-c3', text: 'Tools ready', required: false },
          { id: 'cb-c4', text: 'Material cleared', required: true },
        ],
        mediaRefs: [],
        safetyLevel: 'caution',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 120,
      },
      {
        id: 'cb-s4',
        stepNumber: 4,
        phase: 'document',
        title: 'Document the Jam',
        instruction: 'Photograph the cleared jam area and any material that caused the jam.',
        type: 'photo_required',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'safe',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: true,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 45,
      },
    ],
  },
  {
    id: 'builtin-electrical-panel-fault',
    companyId: 'pulsemaint_templates',
    name: 'Electrical Panel Fault',
    description: 'Triage flow for electrical panel faults. High danger — strict safety protocols.',
    machineTypeId: 'electrical_panel',
    specificMachineId: null,
    language: 'en',
    isTemplate: true,
    isActive: true,
    createdBy: 'system',
    createdAt: now,
    updatedAt: now,
    updatedBy: 'system',
    emergencyContacts: [
      { name: 'Electrical Supervisor', phone: '+94-XX-XXXXXXX', role: 'supervisor' },
      { name: 'Emergency Services', phone: '119', role: 'emergency' },
    ],
    machineShutdownProcedure:
      '1. DO NOT touch the panel\n2. Isolate main supply at DB\n3. Call electrical supervisor immediately\n4. Evacuate area if smoke/fire',
    totalEstimatedMinutes: 5,
    usageCount: 0,
    lastUsedAt: null,
    steps: [
      {
        id: 'ep-s1',
        stepNumber: 1,
        phase: 'safety',
        title: 'DO NOT TOUCH THE PANEL',
        instruction: '⚠ ELECTRICAL HAZARD. Do NOT open or touch the electrical panel. Maintain 1m distance. Check for burning smell or smoke.',
        type: 'yes_no',
        options: [
          { id: 'ep-s1-y', label: 'No smoke/fire visible', nextStepId: 'ep-s2', isEscalate: false, isSafe: true },
          { id: 'ep-s1-n', label: 'Smoke / Fire / Burning smell', nextStepId: null, isEscalate: true, isSafe: false },
        ],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'danger',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 30,
      },
      {
        id: 'ep-s2',
        stepNumber: 2,
        phase: 'assessment',
        title: 'Describe the Fault',
        instruction: 'Without opening the panel, describe what you observe.',
        type: 'multiple_choice',
        options: [
          { id: 'ep-s2-a', label: 'Tripped breaker (visible through window)', nextStepId: 'ep-s3', isEscalate: false, isSafe: true },
          { id: 'ep-s2-b', label: 'Warning light on panel', nextStepId: 'ep-s3', isEscalate: false, isSafe: true },
          { id: 'ep-s2-c', label: 'No power to machine', nextStepId: 'ep-s3', isEscalate: false, isSafe: true },
          { id: 'ep-s2-d', label: 'Unknown / Cannot determine', nextStepId: null, isEscalate: true, isSafe: false },
        ],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'danger',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 45,
      },
      {
        id: 'ep-s3',
        stepNumber: 3,
        phase: 'document',
        title: 'Photograph the Panel',
        instruction: 'From a safe distance, photograph the front of the panel showing any visible indicators.',
        type: 'photo_required',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'danger',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: true,
        requiresConfirmation: false,
        translations: {},
        estimatedSeconds: 30,
      },
      {
        id: 'ep-s4',
        stepNumber: 4,
        phase: 'wait',
        title: 'Wait for Electrician',
        instruction: 'You have completed your assessment safely. Keep the area clear. An electrician must resolve this fault — do NOT attempt any electrical work.',
        type: 'statement',
        options: [],
        checklistItems: [],
        mediaRefs: [],
        safetyLevel: 'caution',
        isEscalationStep: false,
        isQuickFixStep: false,
        requiresPhoto: false,
        requiresConfirmation: true,
        translations: {},
        estimatedSeconds: 30,
      },
    ],
  },
];
