import { Download, Trash2 } from 'lucide-react';
import ReportFormatBadge from './ReportFormatBadge';
import type { ReportHistory } from '../../../types/reports.types';

export default function ReportHistoryCard({
  report,
  onDelete,
}: {
  report: ReportHistory;
  onDelete: (id: string) => void;
}) {
  return (
    <article className="rounded-lg border border-[#1E3A5F] bg-[#0F1E35] p-4 lg:hidden">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h3 className="font-[Sora] text-sm font-semibold text-[#F0F4F8]">{report.reportName}</h3>
          <p className="mt-1 text-xs text-[#8BA3BF]">{report.dateRangeFrom} to {report.dateRangeTo}</p>
        </div>
        <ReportFormatBadge format={report.format} />
      </div>
      <p className="mt-3 text-xs text-[#8BA3BF]">Generated by {report.generatedByName} · {report.generatedAt.toLocaleString()}</p>
      <div className="mt-4 flex gap-2">
        <a href={report.downloadUrl ?? report.googleSheetsUrl ?? '#'} target="_blank" rel="noreferrer" className="inline-flex min-h-11 flex-1 items-center justify-center gap-2 rounded-lg bg-[#1A56DB] px-3 text-sm font-semibold text-white">
          <Download className="h-4 w-4" />
          Open
        </a>
        <button type="button" onClick={() => onDelete(report.id)} className="flex min-h-11 w-12 items-center justify-center rounded-lg border border-[#EF4444]/40 text-[#FCA5A5]" aria-label="Delete history entry">
          <Trash2 className="h-4 w-4" />
        </button>
      </div>
    </article>
  );
}
