import { REPORT_LIST } from '../../../utils/reports/reportDefinitions';
import type { ReportHistoryFilters } from '../../../types/reports.types';

export default function ReportHistoryFilterBar({
  filters,
  onChange,
}: {
  filters: ReportHistoryFilters;
  onChange: (updates: Partial<ReportHistoryFilters>) => void;
}) {
  return (
    <div className="grid gap-3 rounded-lg border border-[#1E3A5F] bg-[#0F1E35] p-4 sm:grid-cols-2 lg:grid-cols-5">
      <select value={filters.reportType} onChange={(event) => onChange({ reportType: event.target.value as ReportHistoryFilters['reportType'] })} className="h-11 rounded-lg border border-[#1E3A5F] bg-[#0A1628] px-3 text-sm text-[#F0F4F8]">
        <option value="all">All reports</option>
        {REPORT_LIST.map((report) => (
          <option key={report.type} value={report.type}>{report.name}</option>
        ))}
      </select>
      <select value={filters.format} onChange={(event) => onChange({ format: event.target.value as ReportHistoryFilters['format'] })} className="h-11 rounded-lg border border-[#1E3A5F] bg-[#0A1628] px-3 text-sm text-[#F0F4F8]">
        <option value="all">All formats</option>
        <option value="pdf">PDF</option>
        <option value="excel">Excel</option>
        <option value="google_sheets">Sheets</option>
      </select>
      <input value={filters.generatedBy} onChange={(event) => onChange({ generatedBy: event.target.value })} placeholder="Generated by" className="h-11 rounded-lg border border-[#1E3A5F] bg-[#0A1628] px-3 text-sm text-[#F0F4F8]" />
      <input type="date" value={filters.dateFrom} onChange={(event) => onChange({ dateFrom: event.target.value })} className="h-11 rounded-lg border border-[#1E3A5F] bg-[#0A1628] px-3 text-sm text-[#F0F4F8]" />
      <input type="date" value={filters.dateTo} onChange={(event) => onChange({ dateTo: event.target.value })} className="h-11 rounded-lg border border-[#1E3A5F] bg-[#0A1628] px-3 text-sm text-[#F0F4F8]" />
    </div>
  );
}
