export { default as DashboardPage } from './DashboardPage';
export { default as SupervisorDashboard } from './SupervisorDashboard';
export { default as ManagerDashboard } from './ManagerDashboard';
export { default as TechnicianDashboard } from './TechnicianDashboard';
export { default as InventoryDashboard } from './InventoryDashboard';
export { default as TrainingDashboard } from './TrainingDashboard';
export { default as TraineeDashboard } from './TraineeDashboard';
export { default as FloorOperatorDashboard } from './FloorOperatorDashboard';
export { default as AdminDashboard } from './AdminDashboard';
