import type { ReportDefinition, ReportType } from '../../types/reports.types';

export const REPORT_DEFINITIONS: Record<ReportType, ReportDefinition> = {
  breakdown_summary: {
    type: 'breakdown_summary',
    name: 'Breakdown Summary Report',
    description: 'Frequency, severity, MTTR, hours lost, and SLA performance for breakdowns.',
    category: 'breakdowns',
    icon: 'AlertTriangle',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'severity', 'breakdown_type'],
    estimatedGenerationSecs: 4,
  },
  work_order_detail: {
    type: 'work_order_detail',
    name: 'Work Order Detail Report',
    description: 'Full work order register with type, priority, assignments, parts, cost, and status.',
    category: 'work_orders',
    icon: 'ClipboardList',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'wo_type', 'technician', 'priority'],
    estimatedGenerationSecs: 5,
  },
  machine_history: {
    type: 'machine_history',
    name: 'Machine History Report',
    description: 'Single-machine profile, breakdowns, maintenance, PMs, parts, and lifetime stats.',
    category: 'machines',
    icon: 'Factory',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Supervisor', 'Technician'],
    availableFilters: ['machine'],
    estimatedGenerationSecs: 7,
  },
  machine_health_score: {
    type: 'machine_health_score',
    name: 'Machine Health Score Report',
    description: 'Fleet health scores, risk distribution, department split, and six-month trends.',
    category: 'machines',
    icon: 'Activity',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department'],
    estimatedGenerationSecs: 4,
  },
  maintenance_cost: {
    type: 'maintenance_cost',
    name: 'Maintenance Cost Report',
    description: 'Parts, labor, contractor spend, cost by department, and expensive machines.',
    category: 'financial',
    icon: 'CircleDollarSign',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager', 'Finance'],
    availableFilters: ['machine', 'department', 'wo_type'],
    estimatedGenerationSecs: 6,
  },
  technician_performance: {
    type: 'technician_performance',
    name: 'Technician Performance Report',
    description: 'Technician workload, response time, repair time, SLA rate, parts usage, and costs.',
    category: 'people',
    icon: 'UsersRound',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'technician'],
    estimatedGenerationSecs: 5,
  },
  contractor_performance: {
    type: 'contractor_performance',
    name: 'Contractor Performance Report',
    description: 'Contractor scoreboard, SLA compliance, first-fix rate, ratings, cost, and invoices.',
    category: 'people',
    icon: 'HardHat',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['contractor'],
    estimatedGenerationSecs: 5,
  },
  contractor_invoice_comparison: {
    type: 'contractor_invoice_comparison',
    name: 'Contractor Invoice Comparison',
    description: 'Contractor invoice values versus system-calculated values and variance bands.',
    category: 'financial',
    icon: 'ReceiptText',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager', 'Finance'],
    availableFilters: ['contractor', 'invoice_status'],
    estimatedGenerationSecs: 4,
  },
  inventory_usage: {
    type: 'inventory_usage',
    name: 'Inventory Usage Report',
    description: 'Issued parts, values, category mix, daily trends, work orders, and technicians.',
    category: 'inventory',
    icon: 'PackageOpen',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['machine', 'part_category'],
    estimatedGenerationSecs: 4,
  },
  parts_consumption: {
    type: 'parts_consumption',
    name: 'Parts Consumption Report',
    description: 'Part consumption totals, value, top categories, and work-order level breakdowns.',
    category: 'inventory',
    icon: 'Boxes',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['machine', 'part_category'],
    estimatedGenerationSecs: 4,
  },
  low_stock_alert: {
    type: 'low_stock_alert',
    name: 'Low Stock Alert Report',
    description: 'Parts below minimum level, out-of-stock items, supplier lead times, and deficits.',
    category: 'inventory',
    icon: 'BellRing',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper'],
    availableFilters: ['part_category'],
    estimatedGenerationSecs: 3,
  },
  pm_compliance: {
    type: 'pm_compliance',
    name: 'PM Compliance Report',
    description: 'Scheduled PM completion, missed tasks, machine and technician compliance pivots.',
    category: 'compliance',
    icon: 'CalendarCheck2',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'technician'],
    estimatedGenerationSecs: 6,
  },
  training_compliance: {
    type: 'training_compliance',
    name: 'Training Compliance Report',
    description: 'Operator certification coverage, expiring certificates, expired records, and matrix.',
    category: 'compliance',
    icon: 'GraduationCap',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['HR', 'Manager'],
    availableFilters: ['training_status'],
    estimatedGenerationSecs: 4,
  },
  sla_compliance: {
    type: 'sla_compliance',
    name: 'SLA Compliance Report',
    description: 'SLA performance by severity, trends, breach detail, department and machine pivots.',
    category: 'compliance',
    icon: 'TimerReset',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'severity', 'sla_status'],
    estimatedGenerationSecs: 5,
  },
  shift_handover_summary: {
    type: 'shift_handover_summary',
    name: 'Shift Handover Summary',
    description: 'Shift acceptance, overlap, watch flags, open work, safety incidents, and notes.',
    category: 'work_orders',
    icon: 'RefreshCw',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Supervisor'],
    availableFilters: ['shift', 'supervisor'],
    estimatedGenerationSecs: 4,
  },
  downtime_analysis: {
    type: 'downtime_analysis',
    name: 'Downtime Analysis Report',
    description: 'Downtime hours, affected machines, production loss, root causes, and incident detail.',
    category: 'breakdowns',
    icon: 'TrendingDown',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager', 'Production'],
    availableFilters: ['machine', 'department', 'severity', 'breakdown_type'],
    estimatedGenerationSecs: 6,
  },
  executive_monthly: {
    type: 'executive_monthly',
    name: 'Executive Monthly Report',
    description: 'Board-ready monthly maintenance narrative, KPI trends, costs, risks, and actions.',
    category: 'executive',
    icon: 'Presentation',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Plant Manager', 'CEO'],
    availableFilters: ['department'],
    estimatedGenerationSecs: 8,
  },
  safety_near_miss: {
    type: 'safety_near_miss',
    name: 'Safety & Near-Miss Report',
    description: 'Safety incidents, near misses, follow-ups, machine history, and department exposure.',
    category: 'compliance',
    icon: 'ShieldAlert',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['HR', 'Manager', 'Compliance'],
    availableFilters: ['shift'],
    estimatedGenerationSecs: 4,
  },
  audit_trail: {
    type: 'audit_trail',
    name: 'Audit Trail Report',
    description: 'System mutation log with user, action, entity, before/after values, and IP context.',
    category: 'compliance',
    icon: 'FileClock',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Compliance', 'HR', 'Admin'],
    availableFilters: [],
    estimatedGenerationSecs: 5,
  },
};

export const REPORT_LIST = Object.values(REPORT_DEFINITIONS);
