import type { TFunction } from 'i18next';
import type { ReportDefinition, ReportType } from '../../types/reports.types';

export const REPORT_DEFINITIONS: Record<ReportType, ReportDefinition> = {
  breakdown_summary: {
    type: 'breakdown_summary',
    name: 'Breakdown Summary Report',
    nameKey: 'common.reports.definitions.breakdown_summary.name',
    description: 'Frequency, severity, MTTR, hours lost, and SLA performance for breakdowns.',
    descriptionKey: 'common.reports.definitions.breakdown_summary.description',
    category: 'breakdowns',
    icon: 'AlertTriangle',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'severity', 'breakdown_type'],
    estimatedGenerationSecs: 4,
  },
  work_order_detail: {
    type: 'work_order_detail',
    name: 'Work Order Detail Report',
    nameKey: 'common.reports.definitions.work_order_detail.name',
    description: 'Full work order register with type, priority, assignments, parts, cost, and status.',
    descriptionKey: 'common.reports.definitions.work_order_detail.description',
    category: 'work_orders',
    icon: 'ClipboardList',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'wo_type', 'priority'],
    estimatedGenerationSecs: 5,
  },
  machine_history: {
    type: 'machine_history',
    name: 'Machine History Report',
    nameKey: 'common.reports.definitions.machine_history.name',
    description: "A machine's full work-order history with types, dates, status, and durations.",
    descriptionKey: 'common.reports.definitions.machine_history.description',
    category: 'machines',
    icon: 'Factory',
    supportsPdf: true,
    supportsExcel: false,
    primaryUsers: ['Supervisor', 'Technician'],
    availableFilters: ['machine'],
    estimatedGenerationSecs: 7,
    // One row per machine's current registry state — no per-row date to filter on.
    supportsDateRange: false,
  },
  machine_health_score: {
    type: 'machine_health_score',
    name: 'Machine Health Score Report',
    nameKey: 'common.reports.definitions.machine_health_score.name',
    description: 'Fleet health scores, risk distribution, department split, and six-month trends.',
    descriptionKey: 'common.reports.definitions.machine_health_score.description',
    category: 'machines',
    icon: 'Activity',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department'],
    estimatedGenerationSecs: 4,
    // Current health scores snapshot — no per-row date to filter on.
    supportsDateRange: false,
  },
  maintenance_cost: {
    type: 'maintenance_cost',
    name: 'Maintenance Cost Report',
    nameKey: 'common.reports.definitions.maintenance_cost.name',
    description: 'Parts, labor, contractor spend, cost by department, and expensive machines.',
    descriptionKey: 'common.reports.definitions.maintenance_cost.description',
    category: 'financial',
    icon: 'CircleDollarSign',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager', 'Finance'],
    availableFilters: ['machine', 'department', 'wo_type'],
    estimatedGenerationSecs: 6,
  },
  technician_performance: {
    type: 'technician_performance',
    name: 'Team Performance Report',
    nameKey: 'common.reports.definitions.technician_performance.name',
    description: 'Per-role performance aggregated from Evaluations, Quick Assessment marks, and Training completions.',
    descriptionKey: 'common.reports.definitions.technician_performance.description',
    category: 'people',
    icon: 'UsersRound',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 5,
    // Lifetime per-person rollup (most recent scores + lifetime totals) — not scoped to a date window.
    supportsDateRange: false,
  },
  contractor_performance: {
    type: 'contractor_performance',
    name: 'Contractor Performance Report',
    nameKey: 'common.reports.definitions.contractor_performance.name',
    description: 'Contractor scoreboard, SLA compliance, first-fix rate, ratings, cost, and invoices.',
    descriptionKey: 'common.reports.definitions.contractor_performance.description',
    category: 'people',
    icon: 'HardHat',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager'],
    availableFilters: ['contractor'],
    estimatedGenerationSecs: 5,
  },
  inventory_usage: {
    type: 'inventory_usage',
    name: 'Inventory Usage Report',
    nameKey: 'common.reports.definitions.inventory_usage.name',
    description: 'Issued parts, values, category mix, daily trends, work orders, and technicians.',
    descriptionKey: 'common.reports.definitions.inventory_usage.description',
    category: 'inventory',
    icon: 'PackageOpen',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['machine', 'part_category'],
    estimatedGenerationSecs: 4,
  },
  low_stock_alert: {
    type: 'low_stock_alert',
    name: 'Low Stock Alert Report',
    nameKey: 'common.reports.definitions.low_stock_alert.name',
    description: 'Parts below minimum level, out-of-stock items, supplier lead times, and deficits.',
    descriptionKey: 'common.reports.definitions.low_stock_alert.description',
    category: 'inventory',
    icon: 'BellRing',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Store Keeper'],
    availableFilters: ['part_category'],
    estimatedGenerationSecs: 3,
    // Current low-stock state snapshot — no per-row date to filter on.
    supportsDateRange: false,
  },
  inventory_listing: {
    type: 'inventory_listing',
    name: 'Inventory Listing Report',
    nameKey: 'common.reports.definitions.inventory_listing.name',
    description: 'All current inventory items with stock levels, cost, supplier, and location details.',
    descriptionKey: 'common.reports.definitions.inventory_listing.description',
    category: 'inventory',
    icon: 'Package',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['part_category'],
    estimatedGenerationSecs: 3,
    // Current inventory catalogue snapshot — no per-row date to filter on.
    supportsDateRange: false,
  },
  pm_compliance: {
    type: 'pm_compliance',
    name: 'PM Compliance Report',
    nameKey: 'common.reports.definitions.pm_compliance.name',
    description: 'Scheduled PM completion, missed tasks, machine and technician compliance pivots.',
    descriptionKey: 'common.reports.definitions.pm_compliance.description',
    category: 'compliance',
    icon: 'CalendarCheck2',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'technician'],
    estimatedGenerationSecs: 6,
  },
  training_compliance: {
    type: 'training_compliance',
    name: 'Training Compliance Report',
    nameKey: 'common.reports.definitions.training_compliance.name',
    description: 'Per-person training coverage across employee and trainee-programme training, with marks.',
    descriptionKey: 'common.reports.definitions.training_compliance.description',
    category: 'compliance',
    icon: 'GraduationCap',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['HR', 'Manager'],
    availableFilters: ['training_type'],
    estimatedGenerationSecs: 4,
    // Lifetime per-person training rollup — not scoped to a date window.
    supportsDateRange: false,
  },
  sla_compliance: {
    type: 'sla_compliance',
    name: 'SLA Compliance Report',
    nameKey: 'common.reports.definitions.sla_compliance.name',
    description: 'SLA performance by severity, trends, breach detail, department and machine pivots.',
    descriptionKey: 'common.reports.definitions.sla_compliance.description',
    category: 'compliance',
    icon: 'TimerReset',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'severity', 'sla_status'],
    estimatedGenerationSecs: 5,
  },
  shift_handover_summary: {
    type: 'shift_handover_summary',
    name: 'Shift Handover Summary',
    nameKey: 'common.reports.definitions.shift_handover_summary.name',
    description: 'Shift acceptance, overlap, watch flags, open work, safety incidents, and notes.',
    descriptionKey: 'common.reports.definitions.shift_handover_summary.description',
    category: 'work_orders',
    icon: 'RefreshCw',
    supportsPdf: true,
    supportsExcel: false,
    primaryUsers: ['Supervisor'],
    availableFilters: ['shift', 'supervisor'],
    estimatedGenerationSecs: 4,
  },
  downtime_analysis: {
    type: 'downtime_analysis',
    name: 'Downtime Analysis Report',
    nameKey: 'common.reports.definitions.downtime_analysis.name',
    description: 'Per-WO downtime (created to signed off) by machine, location, and day of the week.',
    descriptionKey: 'common.reports.definitions.downtime_analysis.description',
    category: 'breakdowns',
    icon: 'TrendingDown',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Manager', 'Production'],
    availableFilters: ['machine', 'department', 'wo_type'],
    estimatedGenerationSecs: 6,
  },
  executive_monthly: {
    type: 'executive_monthly',
    name: 'Executive Monthly Report',
    nameKey: 'common.reports.definitions.executive_monthly.name',
    description: 'Board-ready monthly maintenance narrative, KPI trends, costs, risks, and actions.',
    descriptionKey: 'common.reports.definitions.executive_monthly.description',
    category: 'executive',
    icon: 'Presentation',
    supportsPdf: true,
    supportsExcel: false,
    primaryUsers: ['Plant Manager', 'CEO'],
    availableFilters: ['department'],
    estimatedGenerationSecs: 8,
  },
  audit_trail: {
    type: 'audit_trail',
    name: 'Audit Trail Report',
    nameKey: 'common.reports.definitions.audit_trail.name',
    description: 'Completed Audit module sessions with category, scope, participants, and marks.',
    descriptionKey: 'common.reports.definitions.audit_trail.description',
    category: 'compliance',
    icon: 'FileClock',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Compliance', 'HR', 'Admin'],
    availableFilters: [],
    estimatedGenerationSecs: 5,
  },
  po_history: {
    type: 'po_history',
    name: 'PO History Report',
    nameKey: 'common.reports.definitions.po_history.name',
    description: 'Purchase order register with supplier, parts, invoice-final pricing, dates, and progress.',
    descriptionKey: 'common.reports.definitions.po_history.description',
    category: 'inventory',
    icon: 'ReceiptText',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
  safety_incidents: {
    type: 'safety_incidents',
    name: 'Safety Incidents Report',
    nameKey: 'common.reports.definitions.safety_incidents.name',
    description: 'Register of safety cases — incidents, near-misses, hazards and unsafe acts reported across the plant.',
    descriptionKey: 'common.reports.definitions.safety_incidents.description',
    category: 'compliance',
    icon: 'ShieldAlert',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Safety Officer', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
  work_permit_history: {
    type: 'work_permit_history',
    name: 'Work Permit History Report',
    nameKey: 'common.reports.definitions.work_permit_history.name',
    description: 'Permit-to-Work register — category, validity window, precautions, sign-off outcome and who issued each permit.',
    descriptionKey: 'common.reports.definitions.work_permit_history.description',
    category: 'compliance',
    icon: 'HardHat',
    supportsPdf: true,
    supportsExcel: true,
    primaryUsers: ['Safety Officer', 'Supervisor', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
};

// Executive Monthly Report is removed from the Reports hub UI while staying
// in REPORT_DEFINITIONS (and the backend generator) for any code that still
// references the type directly.
export const REPORT_LIST = Object.values(REPORT_DEFINITIONS).filter(
  (r) => r.type !== 'executive_monthly',
);

/**
 * Resolves a report's display name. Pass `t` (from `useTranslation()`) to
 * get the translated name; omit it (non-component callers with no `t` on
 * hand, e.g. deep export/service helpers) to fall back to the English
 * `name` text — same optional-`t` shape as `buildRange` in
 * MoeMachineFilter.tsx.
 */
export function getReportName(def: ReportDefinition, t?: TFunction): string {
  return t ? t(def.nameKey, { defaultValue: def.name }) : def.name;
}

/** Same as `getReportName`, for the report's description. */
export function getReportDescription(def: ReportDefinition, t?: TFunction): string {
  return t ? t(def.descriptionKey, { defaultValue: def.description }) : def.description;
}
