import type { ReportDefinition, ReportType } from '../../types/reports.types';

export const REPORT_DEFINITIONS: Record<ReportType, ReportDefinition> = {
  breakdown_summary: {
    type: 'breakdown_summary',
    name: 'Breakdown Summary Report',
    description: 'Frequency, severity, MTTR, hours lost, and SLA performance for breakdowns.',
    category: 'breakdowns',
    icon: 'AlertTriangle',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'severity', 'breakdown_type'],
    estimatedGenerationSecs: 4,
  },
  work_order_detail: {
    type: 'work_order_detail',
    name: 'Work Order Detail Report',
    description: 'Full work order register with type, priority, assignments, parts, cost, and status.',
    category: 'work_orders',
    icon: 'ClipboardList',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: ['machine', 'department', 'wo_type', 'priority'],
    estimatedGenerationSecs: 5,
  },
  machine_history: {
    type: 'machine_history',
    name: 'Machine History Report',
    description: "A machine's full work-order history with types, dates, status, and durations.",
    category: 'machines',
    icon: 'Factory',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Supervisor', 'Technician'],
    availableFilters: ['machine'],
    estimatedGenerationSecs: 7,
  },
  machine_health_score: {
    type: 'machine_health_score',
    name: 'Machine Health Score Report',
    description: 'Fleet health scores, risk distribution, department split, and six-month trends.',
    category: 'machines',
    icon: 'Activity',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department'],
    estimatedGenerationSecs: 4,
  },
  maintenance_cost: {
    type: 'maintenance_cost',
    name: 'Maintenance Cost Report',
    description: 'Parts, labor, contractor spend, cost by department, and expensive machines.',
    category: 'financial',
    icon: 'CircleDollarSign',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager', 'Finance'],
    availableFilters: ['machine', 'department', 'wo_type'],
    estimatedGenerationSecs: 6,
  },
  technician_performance: {
    type: 'technician_performance',
    name: 'Team Performance Report',
    description: 'Per-role performance aggregated from Evaluations, Quick Assessment marks, and Training completions.',
    category: 'people',
    icon: 'UsersRound',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Supervisor', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 5,
  },
  contractor_performance: {
    type: 'contractor_performance',
    name: 'Contractor Performance Report',
    description: 'Contractor scoreboard, SLA compliance, first-fix rate, ratings, cost, and invoices.',
    category: 'people',
    icon: 'HardHat',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['contractor'],
    estimatedGenerationSecs: 5,
  },
  inventory_usage: {
    type: 'inventory_usage',
    name: 'Inventory Usage Report',
    description: 'Issued parts, values, category mix, daily trends, work orders, and technicians.',
    category: 'inventory',
    icon: 'PackageOpen',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['machine', 'part_category'],
    estimatedGenerationSecs: 4,
  },
  low_stock_alert: {
    type: 'low_stock_alert',
    name: 'Low Stock Alert Report',
    description: 'Parts below minimum level, out-of-stock items, supplier lead times, and deficits.',
    category: 'inventory',
    icon: 'BellRing',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper'],
    availableFilters: ['part_category'],
    estimatedGenerationSecs: 3,
  },
  inventory_listing: {
    type: 'inventory_listing',
    name: 'Inventory Listing Report',
    description: 'All current inventory items with stock levels, cost, supplier, and location details.',
    category: 'inventory',
    icon: 'Package',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: ['part_category'],
    estimatedGenerationSecs: 3,
  },
  pm_compliance: {
    type: 'pm_compliance',
    name: 'PM Compliance Report',
    description: 'Scheduled PM completion, missed tasks, machine and technician compliance pivots.',
    category: 'compliance',
    icon: 'CalendarCheck2',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'technician'],
    estimatedGenerationSecs: 6,
  },
  training_compliance: {
    type: 'training_compliance',
    name: 'Training Compliance Report',
    description: 'Per-person training coverage across employee and trainee-programme training, with marks.',
    category: 'compliance',
    icon: 'GraduationCap',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['HR', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
  sla_compliance: {
    type: 'sla_compliance',
    name: 'SLA Compliance Report',
    description: 'SLA performance by severity, trends, breach detail, department and machine pivots.',
    category: 'compliance',
    icon: 'TimerReset',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager'],
    availableFilters: ['machine', 'department', 'severity', 'sla_status'],
    estimatedGenerationSecs: 5,
  },
  shift_handover_summary: {
    type: 'shift_handover_summary',
    name: 'Shift Handover Summary',
    description: 'Shift acceptance, overlap, watch flags, open work, safety incidents, and notes.',
    category: 'work_orders',
    icon: 'RefreshCw',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Supervisor'],
    availableFilters: ['shift', 'supervisor'],
    estimatedGenerationSecs: 4,
  },
  downtime_analysis: {
    type: 'downtime_analysis',
    name: 'Downtime Analysis Report',
    description: 'Per-WO downtime (created to signed off) by machine, location, and day of the week.',
    category: 'breakdowns',
    icon: 'TrendingDown',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Manager', 'Production'],
    availableFilters: ['machine', 'department', 'wo_type'],
    estimatedGenerationSecs: 6,
  },
  executive_monthly: {
    type: 'executive_monthly',
    name: 'Executive Monthly Report',
    description: 'Board-ready monthly maintenance narrative, KPI trends, costs, risks, and actions.',
    category: 'executive',
    icon: 'Presentation',
    supportsPdf: true,
    supportsExcel: false,
    supportsSheets: false,
    primaryUsers: ['Plant Manager', 'CEO'],
    availableFilters: ['department'],
    estimatedGenerationSecs: 8,
  },
  audit_trail: {
    type: 'audit_trail',
    name: 'Audit Trail Report',
    description: 'Completed Audit module sessions with category, scope, participants, and marks.',
    category: 'compliance',
    icon: 'FileClock',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Compliance', 'HR', 'Admin'],
    availableFilters: [],
    estimatedGenerationSecs: 5,
  },
  po_history: {
    type: 'po_history',
    name: 'PO History Report',
    description: 'Purchase order register with supplier, parts, invoice-final pricing, dates, and progress.',
    category: 'inventory',
    icon: 'ReceiptText',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Store Keeper', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
  safety_incidents: {
    type: 'safety_incidents',
    name: 'Safety Incidents Report',
    description: 'Register of safety cases — incidents, near-misses, hazards and unsafe acts reported across the plant.',
    category: 'compliance',
    icon: 'ShieldAlert',
    supportsPdf: true,
    supportsExcel: true,
    supportsSheets: true,
    primaryUsers: ['Safety Officer', 'Manager'],
    availableFilters: [],
    estimatedGenerationSecs: 4,
  },
};

export const REPORT_LIST = Object.values(REPORT_DEFINITIONS);
