import { useTranslation } from 'react-i18next';
import type { ParsedPartRow } from '@/types/inventory';

interface ImportPreviewTableProps {
  rows: ParsedPartRow[];
  createCount: number;
  updateCount: number;
  existingPartNumbers: Set<string>;
}

export function ImportPreviewTable({
  rows,
  createCount,
  updateCount,
  existingPartNumbers,
}: ImportPreviewTableProps) {
  const { t } = useTranslation();
  const previewRows = rows.slice(0, 10);

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between flex-wrap gap-2">
        <p className="text-sm text-gray-600">
          {t('common.inventory.import.previewTable.showingRows', { shown: previewRows.length, total: rows.length })}
        </p>
        <p className="text-sm font-medium text-gray-800">
          <span className="text-green-700">
            {t('common.inventory.import.previewTable.newPartsWillBeCreated', { count: createCount })}
          </span>
          {updateCount > 0 && (
            <>
              {' · '}
              <span className="text-blue-700">
                {t('common.inventory.import.previewTable.partsWillBeUpdated', { count: updateCount })}
              </span>
            </>
          )}
        </p>
      </div>

      <div className="overflow-x-auto border border-gray-200 rounded-xl">
        <table className="w-full text-xs">
          <thead className="bg-gray-50">
            <tr>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.partNumber')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.partName')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.category')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.unit')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.stock')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.unitCost')}</th>
              <th className="px-3 py-2 text-left font-semibold text-gray-700 whitespace-nowrap">{t('common.inventory.import.previewTable.columns.action')}</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-gray-100">
            {previewRows.map((row) => {
              const isUpdate = existingPartNumbers.has(row.partNumber);
              return (
                <tr
                  key={row.rowIndex}
                  className={`border-l-4 ${isUpdate ? 'border-l-blue-500 bg-blue-50/30' : 'border-l-green-500 bg-green-50/30'}`}
                >
                  <td className="px-3 py-2 font-mono font-medium text-gray-900">
                    {row.partNumber || <span className="italic text-gray-400 font-sans">{t('common.inventory.import.previewTable.autoGenerated')}</span>}
                  </td>
                  <td className="px-3 py-2 text-gray-800 max-w-[160px] truncate">{row.name}</td>
                  <td className="px-3 py-2 text-gray-600">{row.category || ''}</td>
                  <td className="px-3 py-2 text-gray-600">{row.unit || ''}</td>
                  <td className="px-3 py-2 text-gray-800">{row.currentStock || '0'}</td>
                  <td className="px-3 py-2 text-gray-800">{row.unitCost ? `LKR ${row.unitCost}` : ''}</td>
                  <td className="px-3 py-2">
                    <span
                      className={`px-2 py-0.5 rounded-full text-xs font-bold uppercase tracking-wide
                        ${isUpdate ? 'bg-blue-100 text-blue-700' : 'bg-green-100 text-green-700'}
                      `}
                    >
                      {isUpdate
                        ? t('common.inventory.import.previewTable.actionUpdate')
                        : t('common.inventory.import.previewTable.actionCreate')}
                    </span>
                  </td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}
