import * as functions from 'firebase-functions';
import * as admin from 'firebase-admin';

if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();
const storage = admin.storage();

function buildHtml(session: FirebaseFirestore.DocumentData, sessionId: string): string {
  const startedAt = (session.startedAt as admin.firestore.Timestamp).toDate().toLocaleString();
  const completedAt = session.completedAt
    ? (session.completedAt as admin.firestore.Timestamp).toDate().toLocaleString()
    : 'In Progress';

  const stepsHtml = (session.stepLogs as Array<Record<string, unknown>>)
    .map(
      (log) => `
    <div class="step">
      <h3>#${log.stepNumber as number} ${log.title as string}</h3>
      <p>Phase: ${log.phase as string} | Duration: ${log.durationSeconds as number}s</p>
      ${log.response !== null ? `<p>Response: <strong>${String(log.response)}</strong></p>` : ''}
      ${log.notes ? `<p>Notes: ${log.notes as string}</p>` : ''}
      ${log.skipped ? `<p>Skipped: ${log.skipReason as string}</p>` : ''}
    </div>
  `
    )
    .join('');

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Triage Report — ${session.machineName as string}</title>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #1a1a1a; }
    h1 { color: #0A1628; }
    .meta { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin: 20px 0; }
    .meta-item { background: #f8f9fa; padding: 12px; border-radius: 8px; }
    .meta-item label { font-size: 11px; color: #666; display: block; margin-bottom: 4px; }
    .meta-item span { font-weight: 600; font-size: 14px; }
    .step { border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin: 8px 0; }
    .step h3 { margin: 0 0 8px; font-size: 15px; }
    .step p { margin: 4px 0; font-size: 13px; color: #444; }
    .outcome { background: #ecfdf5; border-left: 4px solid #10B981; padding: 16px; margin: 20px 0; border-radius: 8px; }
  </style>
</head>
<body>
  <h1>Triage Report</h1>
  <div class="meta">
    <div class="meta-item"><label>Machine</label><span>${session.machineName as string}</span></div>
    <div class="meta-item"><label>Flow</label><span>${session.flowName as string}</span></div>
    <div class="meta-item"><label>Supervisor</label><span>${session.supervisorName as string}</span></div>
    <div class="meta-item"><label>Status</label><span>${session.status as string}</span></div>
    <div class="meta-item"><label>Started</label><span>${startedAt}</span></div>
    <div class="meta-item"><label>Completed</label><span>${completedAt}</span></div>
  </div>
  ${session.outcomeType ? `<div class="outcome"><strong>Outcome:</strong> ${session.outcomeType as string}<br>${session.outcomeNotes ? session.outcomeNotes as string : ''}</div>` : ''}
  <h2>Step Log</h2>
  ${stepsHtml || '<p>No steps logged.</p>'}
  <p style="margin-top:40px;font-size:11px;color:#999;">Generated by PulseMaint — Session ID: ${sessionId}</p>
</body>
</html>`;
}

export const generateTriageReportPdf = functions.https.onCall(async (data, context) => {
  if (!context.auth) {
    throw new functions.https.HttpsError('unauthenticated', 'Must be authenticated');
  }

  const { sessionId } = data as { sessionId: string };
  if (!sessionId) {
    throw new functions.https.HttpsError('invalid-argument', 'sessionId required');
  }

  const snap = await db.collection('triageSessions').doc(sessionId).get();
  if (!snap.exists) {
    throw new functions.https.HttpsError('not-found', 'Session not found');
  }

  const session = snap.data()!;
  const html = buildHtml(session, sessionId);

  // Store HTML as a "report" (Puppeteer would convert to PDF in production)
  const bucket = storage.bucket();
  const path = `triageReports/${sessionId}/report.html`;
  const file = bucket.file(path);

  await file.save(Buffer.from(html, 'utf-8'), {
    metadata: { contentType: 'text/html' },
  });

  const [url] = await file.getSignedUrl({
    action: 'read',
    expires: Date.now() + 7 * 24 * 60 * 60 * 1000, // 7 days
  });

  return { url };
});
